export const openApi = {
  openapi: "3.0.3",
  info: {
    title: "FinOps AI Copilot Foundation API",
    version: "1.0.0",
  },
  servers: [{ url: "http://localhost:8080/api/v1" }],
  paths: {
    "/auth/login": { post: { summary: "Authenticate with email and password" } },
    "/auth/register": { post: { summary: "Create organization and owner user" } },
    "/auth/logout": { post: { summary: "Invalidate current session" } },
    "/auth/refresh": { post: { summary: "Rotate refresh token" } },
    "/auth/forgot-password": { post: { summary: "Create reset token without email enumeration" } },
    "/auth/reset-password": { post: { summary: "Reset password with token" } },
    "/auth/mfa/verify": { post: { summary: "Verify MFA token" } },
    "/auth/mfa/setup": { post: { summary: "Begin MFA enrollment" } },
    "/auth/mfa/confirm": { post: { summary: "Confirm MFA enrollment" } },
    "/auth/oauth/{provider}": { get: { summary: "Start OAuth login flow" } },
    "/organization": { get: { summary: "Get current organization" }, patch: { summary: "Update current organization" } },
    "/organization/onboarding": { post: { summary: "Complete organization onboarding" } },
    "/users": { get: { summary: "List organization users" } },
    "/users/invite": { post: { summary: "Invite organization users" } },
    "/users/{id}": { patch: { summary: "Update user role/status" }, delete: { summary: "Soft-delete user" } },
    "/api-keys": { get: { summary: "List API keys" }, post: { summary: "Create API key" } },
    "/api-keys/{id}": { delete: { summary: "Revoke API key" } },
    "/audit-logs": { get: { summary: "Search immutable audit logs" } },
    "/sessions": { get: { summary: "List active sessions" } },
    "/sessions/{id}": { delete: { summary: "Revoke session" } },
    "/dashboard/summary": { get: { summary: "Foundation dashboard summary" } },
    "/health": { get: { summary: "Health check" } },
  },
};
